### ISSUE TITLE
Usage of deprecated SonarQube API < 5.6

### ISSUE THREAD

**Issue by dbmeneses** [sfeir-open-source/sonar-clover#11]
The SonarQube API that was deprecated before version 5.6 will be dropped soon.
It can be tested with SonarQube artifact 7.0.0.34895 (or newer one from the branch 'feature/dm/sq56').

More information: https://jira.sonarsource.com/browse/SONAR-10138

**Comment by mlschechter** [comment]
This should be addressed by my [pull request](https://github.com/Tony-Proum/sonar-clover/pull/15). Please let me know if you have any questions.

**Comment by Tony-Proum** [comment]
Closed as duplicate of https://github.com/sfeir-open-source/sonar-clover/issues/18
