### ISSUE TITLE
Find a directory to deploy our artifacts 

### ISSUE THREAD

**Issue by Tony-Proum** [sfeir-open-source/sonar-clover#24]
seems like something went wrong when uploading artifacts to repository see : https://travis-ci.org/Tony-Proum/sonar-clover/jobs/446242289

**Comment by Tony-Proum** [comment]
We should be able to have an Artifactory account for this project. I'm on it

**Comment by heruan** [comment]
Any progress on this?

**Comment by Tony-Proum** [comment]
I'm working with jfrog tools and team in order to see which type of account should be use. Also, this repository will be transferred under an organization that I would like to work with (As it should help me to have more time to work on this project and sould help to get more devs involve in the project. It should allows the plugin to evolve faster)

**Comment by Tony-Proum** [comment]
FYI an oss artifactory/bintray account may be use to store our artifacts.

**Comment by heruan** [comment]
Not sure I'm following: won't this be available in Maven Central?

**Comment by Tony-Proum** [comment]
The build tools used for this plugin is the same as the official plugins supported by sonarSource so we should not have any issue to use it in a clean SonarQube install. Also I don't know how it works for other plugins (maven central or directly jfrog jcenter) but using Jcenter, it still be possible to upload artifacts on maven central.

**Comment by mlschechter** [comment]
@Tony-Proum.

I'll have some time next week to help out if you've got some tasks I can work on. Also, I'm going to look at removing the deprecated XML-handling code so that the new version will be completely clean and compatible with SQ 7.2+

**Comment by seenusankara** [comment]
@mlschechter ,  can I have the release date for the new version which is supported for SonarQube 7.4 or 7.2

**Comment by mlschechter** [comment]
@seenusankara,

I've updated my pull request to remove the deprecated code, and verified it works against 7.4 (sort of - as of 7.2 the Groovy plugin is no longer supported, so the Groovy-based integration test fails).

@Tony-Proum can provide more input on a release schedule; it looks like there are still some issues to be resolved before my code can be merged.

**Comment by cesares-basilico** [comment]
@Tony-Proum any news about the release of the fixed plugin? Can you please push the changes so we can build it locally while you find a directory to deploy?

**Comment by Tony-Proum** [comment]
I'll transfer this repository to a new organization in order to provide a better support. The organization could help to update the plugin faster. 
I've not been able to do It before, but this transfer should happen soon, this way more people should be able to contribute.

**Comment by heruan** [comment]
Any update?

**Comment by Tony-Proum** [comment]
Hello, the plugin has been transferred to the organization. We are not able to build it and to deal with the licence. Also we're now able to get some quality analysis using sonarCloud plateform (AFAIK it's mandatory to create a plugin that's allowed to be published in the sonarQube market place) you can see the result here https://sonarcloud.io/dashboard?id=sfeir-open-source_sonar-clover
In order to go further, we have to link the organization with an artifact repository, for now, I'm trying to have more informations about this topic, I'll keep you inform

**Comment by Tony-Proum** [comment]
FYI, now our artifacts can be uploade to Jfrog Bintray, all checks are ok. We are now trying to fix some issue to integrate the plugin with the market place but this issue is now fixed
