### ISSUE TITLE
No plugin descriptor found at META-INF/maven/plugin.xml

### ISSUE THREAD

**Issue by fmcarvalho** [sfeir-open-source/sonar-clover#41]
**Describe the bug**

After the installation locally of release 4.1 when we run: `mvn org.sfeir:sonar-clover-plugin:4.1:sonar`

I got:  `No plugin descriptor found at META-INF/maven/plugin.xml`

**To Reproduce**
1. Install locally through `mvn install:install-file -Dfile=sonar-clover-plugin-4.1.jar -DgroupId=org.sfeir -DartifactId=sonar-clover-plugin -Dversion=4.1 -Dpackaging=jar -DgeneratePom=true`
2. Run `mvn org.sfeir:sonar-clover-plugin:4.1:sonar`
3. See error `[ERROR] Failed to parse plugin descriptor for org.sfeir:sonar-clover-plugin:4.1 (C:\Users\migue\.m2\repository\org\sfeir\sonar-clover-plugin\4.1\sonar-clover-plugin-4.1.jar): No plugin descriptor found at META-INF/maven/plugin.xml` 

**Expected behavior**

`[ERROR] Failed to execute ...(default-cli): Goal requires`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Maven: `Apache Maven 3.6.1``
- Java version: 11.0.5

**Comment by Tony-Proum** [comment]
Hi @fmcarvalho this plugin is not the maven one but the sonarqube plugin, you can install it using sonarqube marketplace:
![image](https://user-images.githubusercontent.com/7056468/81502933-4455ec00-92e1-11ea-80ee-dd0b7adf3968.png)
I think that the one you would like to use is located here : https://github.com/openclover/clover-maven-plugin
