### ISSUE TITLE
Bintray has removed the link to the binary (404) 

### ISSUE THREAD

**Issue by datenzar** [sfeir-open-source/sonar-clover#49]
**Describe the bug**
When trying to download the binary package at https://bintray.com/sfeir-open-source/maven/sonar-clover/4.1/link I get a 404 message. 

Is there any other source to download the jar without having to compile it?

**Comment by Tony-Proum** [comment]
Hi, 
I' m working on it, see more : 
https://github.com/sfeir-open-source/sonar-clover/issues/47

**Comment by Tony-Proum** [comment]
Hi, 
The 4.1 is now back on the marketplace sorry for the inconvenience
