### ISSUE TITLE
Plugin to be made avilable in sonarsource distribution

### ISSUE THREAD

**Issue by shourien** [sfeir-open-source/sonar-clover#51]
**Is your feature request related to a problem? Please describe.**
A It would be beneficial to officially publish the plugin through the sonar sources https://binaries.sonarsource.com/Distribution/sonar-clover/ also.

**Describe the solution you'd like**
A I do see plugin 3.1 being published in the above link but nothing after that

**Describe alternatives you've considered**
A Current alternative was to procure the plugin from bintray or maven repo. But automated systems that deploy sonarqube servers need to deviate and download this plugin from maven/bintray

**Additional context**
An official distribution through sonarsouce site could possibly be useful to circumvent https://github.com/sfeir-open-source/sonar-clover/issues/47 potentially

https://binaries.sonarsource.com/Distribution/sonar-clover/

**Comment by Tony-Proum** [comment]
Hi @shourien 

I think that this binaries are related to plugin maintained by sonarsource. The sonar-clover plugin is now a community plugin so we have to found our own way to store artifacts. 

The previous version (under 3.1, were maintained by sonarsource itself)
